[package]
name = "boringtun-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
surf = "2.3.2"

[dependencies.tokio]
version = "1.15"
features = ["full"]
