[package]
name = "catsay"
version = "0.1.0"
edition = "2021"
authors=['Mihail Gaberov <mihail.gaberov@gmail.com>']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="0.2.15"